blog/urls.py
from django.urls import path
from .views import (ArticleList,ArticleDetail,CategoryList,
                    AuthorList,ArticlePreview,SearchList,
                    about)

app_name = "blog"

urlpatterns = [
    path('', ArticleList.as_view(),name= "home"),
    path('page/<int:page>', ArticleList.as_view(),name= "home"),
    
    path('about/', about,name= "about"),

    
    path('article/<slug:slug>/',ArticleDetail.as_view(),name= "detail"),
    path('preview/<int:pk>/',ArticlePreview.as_view(),name= "preview"),
    
    path('category/<slug:slug>/',CategoryList.as_view(),name="category"),
    path('category/<slug:slug>/page/<int:page>',CategoryList.as_view(),name="category"),
    
    path('author/<slug:username>',AuthorList.as_view(),name = 'author'),
    path('author/<slug:username>/page/<int:page>',AuthorList.as_view(),name = 'author'),
    
    path('search/',SearchList.as_view(),name = 'search'),
    path('search/page/<int:page>',SearchList.as_view(),name = 'search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from account.views import Login,activate,Register



urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('login/', Login.as_view(), name='login'),
    
    path("register/", Register.as_view(), name="register"),
    
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
 
    path('', include('blog.urls')),
    
    path('account/', include('account.urls')),
    
    path('contact/', include('contact.urls')),
    
    path('', include('django.contrib.auth.urls')),
    
    path('', include('social_django.urls', namespace='social')),
]


# from django.conf import settings
# from django.conf.urls.static import static
# urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import contact

app_name = "contact"

urlpatterns = [
    path('pages/', contact,name= "contact"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_conveter
from django.utils.html import format_html
from account.models import User
from django.urls import reverse






# my managersclass
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')
    

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)
    


class Category(models.Model):
    # parent = models.ForeignKey('self',default=None,null=True,blank=True,on_delete=models.SET_NULL,related_name='children',verbose_name='زیر دسته')
    title = models.CharField(max_length = 200,verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length = 100,unique = True,verbose_name='آدرس دسته بندی')
    status = models.BooleanField(default=True,verbose_name="نمایش دادن")
    position = models.IntegerField(verbose_name="موقعیت دسته بندی")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['position']
        
    def __str__(self):
        return self.title

    objects= CategoryManager()
class Article(models.Model):
    
    STATUS_CHOICES = (
        ('d','پیش نویس'),
        ('p','منتشر شده'),
        ('i',' در حال بررسی'),
        ('b',' برگشت داده شده'), #back
    )
    author = models.ForeignKey(User,null=True,on_delete=models.SET_NULL,related_name="articles",verbose_name="نویسنده")
    title = models.CharField(max_length = 200,verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length = 100,unique = True,verbose_name='آدرس مقاله')
    description = models.TextField(verbose_name='محتوا')
    category = models.ManyToManyField(Category,verbose_name="دسته بندی",related_name="articles")
    thumbnail = models.ImageField(upload_to = 'images',verbose_name="تصویر مقاله")
    publish = models.DateTimeField(default = timezone.now,verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 1,choices = STATUS_CHOICES,verbose_name='وضعیت')
    is_special = models.BooleanField(default=False,verbose_name= "مقاله ویژه")
    
    
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ['-publish']
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("account:home")
    
    def jpublish(self):
        return jalali_conveter(self.publish)
    jpublish.short_description = "زمان انتشار"
    
    def thumbnail_tag(self):
            return format_html("<img src='{}' width=55px hieght=35px style='border-radius:10px'; >".format(self.thumbnail.url))
    thumbnail_tag.short_description = "تصویر مقاله"
    
    def category_to_str(self):
        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description = "دسته بندی"
    
    objects= ArticleManager()    
    

contact/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100,verbose_name="نام")
    email = models.EmailField(max_length=100,verbose_name="ایمیل")
    message = models.TextField(blank=True,verbose_name="متن")
    
    class Meta:
        verbose_name="مخاطبین"
        verbose_name_plural="مخاطبین ها"
    
    def __str__(self) :
        return self.email   
    

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article,Category
from django.views.generic import ListView,DetailView
from account.models import User
from account.mixins import AuthorAccessMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q



class ArticleList(ListView):
 
    queryset = Article.objects.published()
    paginate_by =  12
    


class ArticleDetail(DetailView):

    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(),slug=slug)
   
            
class CategoryList(ListView):
    template_name = "blog/category_list.html"
    paginate_by =  12
    
    def get_queryset(self):
        global category
        slug  = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(),slug=slug) 
        return category.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context
    
    
class AuthorList(ListView):
    template_name = "blog/author_list.html"
    paginate_by =  12
    
    def get_queryset(self):
        global author
        username  = self.kwargs.get('username')
        author = get_object_or_404(User,username=username)  
       
        return author.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context
    
    
class ArticlePreview(AuthorAccessMixin,DetailView):
    template_name = "blog/article_detail.html"
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article,pk=pk)
    
    

class SearchList(ListView):
    paginate_by = 5
    template_name = 'blog/search_list.html'
    
    def get_queryset(self):
        global search
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains = search) | Q(title__icontains = search))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = search
        return context
    
    
    
def about(request):
    return render(request,"blog/about.html")

contact/views.py
from django.shortcuts import render

from contact.models import Contact
from .forms import ContactForm

def contact(request):
    response_from = ContactForm()
    if request.method == "POST":
        response_from = ContactForm(request.POST)
        if response_from.is_valid():
            response_from.save()
    else:
        response_from = ContactForm()
        
    context={
        'form':response_from
    }
    return render(request,"blog/contact.html",context)

templates/blog/article_detail.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}
| {{article.title|truncatewords:5}}
{% endblock %}

{% block main %}
       <!-- content
    ================================================== -->
    <section class="s-content">

        <div class="row">
            <div class="column large-12">
            
                <article class="s-content__entry">

                    <div class="s-content__media">
                        <img src="{{object.thumbnail.url}}" width="100%"
                                srcset="{{object.thumbnail.url}} 2100w, 
                                        {{object.thumbnail.url}} 1050w, 
                                        {{object.thumbnail.url}} 525w" sizes="(max-width: 2100px) 100vw, 2100px" alt="{{object.title}}">
                                        <small>{{ object.jpublish }}</small>
                                        
                    </div> <!-- end s-content__media -->

                    
               
                    <div class="s-content__entry-header">
                       
                                <h1 class="s-content__title">
                                    {{ object.title }}
                                    {% if article.is_special %}

                                    <span style="background-color: #4a66e4;color:#fffff0;opacity: 0.5;outline: 0;border: 0;border-radius: 5px;">(ویژه)</span>
            
                                {% endif %}
                                </h1>
                        
                    </div> <!-- end s-content__entry-header -->

                    <div class="s-content__primary">

                        <div class="s-content__page-content">

                            <p class="lead">
                                {% if object.is_special %}
                                {% if user.is_authenticated and user.is_special or user == object.author or user.is_superuser %}
                                    {{object.description|safe}}
                                {% else %}
                                    {{article.description|striptags|truncatewords:30}}
                                <p class="lead">
                                    این مقاله ویژه است   برای مشاهده ان باید اشتراک ویژه تهیه کنید
                                </p>
                                {% endif %}
                            {% else %}
                                {{object.description|safe}}
                            {% endif %}
                                
                            </p>
                        
                            <br>
                          
                        </div> <!-- end s-entry__page-content -->

                    </div> <!-- end s-content__primary -->
                </article> <!-- end entry -->

            </div> <!-- end column -->
        </div> <!-- end row -->

          
    
    </section> <!-- end s-content -->


{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}
{% block header %}
{% endblock %}


{% block previous_page_url %} 
    {% url 'blog:home'  page_obj.previous_page_number %}
{% endblock%}


{% block next_page_url %}
    {% url 'blog:home'  page_obj.next_page_number %}
{% endblock %}


{% block range_1 %}
    {% url 'blog:home' i %}
{% endblock %}

{% block range_2 %}
    {% url 'blog:home' i %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block header %}
<!-- page header
        ================================================== -->
        <div class="s-pageheader">
            <div class="row">
                <div class="column large-12">
                    <h1 class="page-title">
                        <span class="page-title__small-type" style="font-size:30px;">نویسنده : <a href="{% url 'blog:author' author.username %}">{{author.get_full_name}}</a></span><br>
                    </h1>
                </div>
            </div>
        </div> 
<!-- end s-pageheader-->
{% endblock %}



{% block previous_page_url %} 
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock%}

{% block range_1 %}
    {% url 'blog:author' author.username i %}
{% endblock %}

{% block range_2 %}
    {% url 'blog:author' author.username i %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>کالوین بلاگ {% block title %}
    
    {% endblock %}</title>
    <meta name="description" content="i am programmer">
    <meta name="ali" content="ali esmaeili">
    <meta name="theme-color" content="#5125a4">


    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'blog/css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/rtl.css' %}">

    <!-- script
    ================================================== -->
    <script src="{% static 'blog/js/modernizr.js' %}"></script>
    <script defer src="{% static 'blog/js/fontawesome/all.min.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'blog/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'blog/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'blog/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'blog/site.webmanifest' %}">

</head>

<body id="top">


    <!-- preloader
    ================================================== -->
    <div id="preloader"> 
    	<div id="loader"></div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header">

        <div class="s-header__logo">
            <a class="logo" href="{% url 'blog:home' %}">
                <img src="{% static 'blog/images/logo.svg' %}" alt="Homepage">
            </a>
        </div>

        {% cetagory_navbar %}

        <a class="s-header__toggle-menu" href="#0" title="Menu"><span>منو</span></a>

        <div class="s-header__search">

            <div class="s-header__search-inner">
                <div class="row wide">

                    <form role="search" class="s-header__search-form" action="{% url 'blog:search' %}">
                        <label>
                            <span class="h-screen-reader-text">جستجو...:</span>
                            <input type="search" class="s-header__search-field" placeholder="جستجو ..." name="q" title="جستجو" >
                        </label>
                        <input type="submit" class="s-header__search-submit" value="جستجو"> 
                    </form>

                    <a href="#0" title="Close Search" class="s-header__overlay-close">بستن</a>

                </div> <!-- end row -->
            </div> <!-- s-header__search-inner -->

        </div> <!-- end s-header__search wrap -->	

        <a class="s-header__search-trigger" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17.982 17.983"><path fill="#010101" d="M12.622 13.611l-.209.163A7.607 7.607 0 017.7 15.399C3.454 15.399 0 11.945 0 7.7 0 3.454 3.454 0 7.7 0c4.245 0 7.699 3.454 7.699 7.7a7.613 7.613 0 01-1.626 4.714l-.163.209 4.372 4.371-.989.989-4.371-4.372zM7.7 1.399a6.307 6.307 0 00-6.3 6.3A6.307 6.307 0 007.7 14c3.473 0 6.3-2.827 6.3-6.3a6.308 6.308 0 00-6.3-6.301z"/></svg>
        </a>

    </header> <!-- end s-header -->


 

    {% block main %}
    
    {% endblock %}

   <!-- footer
    ================================================== -->
    <footer class="s-footer">

        <div class="s-footer__main">

            <div class="row">

                <div class="column large-3 medium-6 tab-12 s-footer__info">

                    <h5>درباره سایت</h5>

                    <p>
                        این وبسایت، یک سیستم عامل و نرم افزار رایگان بوده که در عین سادگی، ویژگی های بسیاری در اختیار شما خواهد گذاشت. ما این سیستم مدیریت محتوا را، برای وبلاگ نویسان جدی خود پیشنهاد میکنیم. این ابزار به شما امکان می دهد در عرض چند دقیقه وب سایت وبلاگ را از ابتدا راه اندازی کنید.
                    </p>

                </div> <!-- end s-footer__info -->

                <div class="column large-2 medium-3 tab-6 s-footer__site-links">

                    <h5>پیوند های سایت</h5>

                    <ul>
                        <li><a href="#0">About Us</a></li>
                        <li><a href="#0">Blog</a></li>
                        <li><a href="#0">FAQ</a></li>
                        <li><a href="#0">Terms</a></li>
                        <li><a href="#0">Privacy Policy</a></li>
                    </ul>

                </div> <!-- end s-footer__site-links -->  

                <div class="column large-2 medium-3 tab-6 s-footer__social-links">

                    <h5>ما را دنبال کنید</h5>

                    <ul>
                        <li><a href="https://www.telegram.com">Telegram  <i class="fab fa-telegram" aria-hidden="true"></i></a></li>
                        <li><a href="https://www.facebook.com">Facebook  <i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                        <li><a href="https://www.linkedin.com">Linkedin  <i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                        <li><a href="https://www.github.com">Github     <i class="fab fa-github" aria-hidden="true"></i></a></li>
                        <li><a href="https://www.instagram.com">Instagram  <i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>

                </div> <!-- end s-footer__social links --> 

                <div class="column large-3 medium-6 tab-12 s-footer__subscribe">

                    <h5>برای خبرنامه ثبت نام کنید</h5>

                  <p>برای دریافت به روز رسانی مقالات، مصاحبه ها و رویدادها ثبت نام کنید</p>

                    <div class="subscribe-form">
                
                        <form id="mc-form" class="group" novalidate="true">

                            <input type="email" value="" name="dEmail" class="email" id="mc-email" placeholder="ایمیل" required=""> 
                
                            <input type="submit" name="subscribe" value="ارسال" >
                
                            <label for="mc-email" class="subscribe-message"></label>
                
                        </form>

                    </div>

                </div> <!-- end s-footer__subscribe -->

            </div> <!-- end row -->

        </div> <!-- end s-footer__main -->

        <div class="s-footer__bottom">
            <div class="row">
                <div class="column">
                    <div class="ss-copyright">
                        <span>© {% now 'Y' %}</span> 
                        <span>طراحی شده توسط: <a href="https://www.instagram.com/esmaeilii7">علی اسماعیلی</a></span>
                    </div> <!-- end ss-copyright -->
                </div>
            </div> 

            <div class="ss-go-top">
                <a class="smoothscroll" title="Back to Top" href="#top">
                    <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" width="15" height="15"><path d="M7.5 1.5l.354-.354L7.5.793l-.354.353.354.354zm-.354.354l4 4 .708-.708-4-4-.708.708zm0-.708l-4 4 .708.708 4-4-.708-.708zM7 1.5V14h1V1.5H7z" fill="currentColor"></path></svg>
                </a>
            </div> <!-- end ss-go-top -->
        </div> <!-- end s-footer__bottom -->

   </footer> <!-- end s-footer -->


    <!-- Java Script
    ================================================== -->
    <script src="{% static 'blog/js/jquery-3.5.0.min.js' %}"></script>
    <script src="{% static 'blog/js/plugins.js' %}"></script>
    <script src="{% static 'blog/js/main.js' %}"></script>

</body>

</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}
{% block title %}
  | دسته بندی:  {{category.title}}
{% endblock %}
{% block header %}
<!-- page header
        ================================================== -->
        <div class="s-pageheader">
            <div class="row">
                <div class="column large-12">
                    <h1 class="page-title">
                        <span class="page-title__small-type" style="font-size:30px;">دسته بندی : <a href="{% url 'blog:category' category.slug %}">{{category.title}}</a></span><br>
                    </h1>
                </div>
            </div>
        </div> 
<!-- end s-pageheader-->
{% endblock %}



{% block previous_page_url %} 
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock%}

{% block range_1 %}
    {% url 'blog:category' category.slug i %}
{% endblock %}

{% block range_2 %}
    {% url 'blog:category' category.slug i %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block main %}

        <section id="hero" class="s-hero">

            <div class="s-hero__slider">

                <div class="s-hero__slide">

                    <div class="s-hero__slide-bg"
                        style="background-image: url('{% static 'blog/images/slide1-bg-3000.jpg' %}');"></div>

                    
                </div> <!-- end s-hero__slide -->

                <div class="s-hero__slide">

                    <div class="s-hero__slide-bg"
                        style="background-image: url('{% static 'blog/images/slide2-bg-3000.jpg' %}' );"></div>

                    
                </div> <!-- end s-hero__slide -->

                <div class="s-hero__slide">

                    <div class="s-hero__slide-bg"
                        style="background-image: url('{% static 'blog/images/slide3-bg-3000.jpg' %}');"></div>


                </div> <!-- end s-hero__slide -->

            </div> <!-- end s-hero__slider -->

            <div class="s-hero__social hide-on-mobile-small">
                <p>Follow</p>
                <span></span>
                <ul class="s-hero__social-icons">
                    <li><a href="#0"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                    <li><a href="#0"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#0"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                    <li><a href="#0"><i class="fab fa-dribbble" aria-hidden="true"></i></a></li>
                </ul>
            </div> <!-- end s-hero__social -->

            <div class="nav-arrows s-hero__nav-arrows">
                <button class="s-hero__arrow-prev">
                    <svg viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg" width="15" height="15">
                        <path d="M1.5 7.5l4-4m-4 4l4 4m-4-4H14" stroke="currentColor"></path>
                    </svg>
                </button>
                <button class="s-hero__arrow-next">
                    <svg viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg" width="15" height="15">
                        <path d="M13.5 7.5l-4-4m4 4l-4 4m4-4H1" stroke="currentColor"></path>
                    </svg>
                </button>
            </div> <!-- end s-hero__arrows -->

        </section>



    <!-- content
    ================================================== -->
    <section class="s-content">


        {% block header %}
        
        {% endblock %}
        

        <!-- masonry
        ================================================== -->
        <div class="s-bricks s-bricks--half-top-padding">

            <div class="masonry">
                <div class="bricks-wrapper h-group">

                    <div class="grid-sizer"></div>

                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>

                    {% for article in object_list %}
                        <article class="brick entry" data-aos="fade-up">
        
                            <div class="entry__thumb">
                                <a href="{% url 'blog:detail' article.slug %}" class="thumb-link">
                                    <img src="{{article.thumbnail.url}}" width="100%"
                                        srcset="{{article.thumbnail.url}} 1x, {{article.thumbnail.url}} 2x" alt="{{article.title}}">
                                    </a>
                                </div> <!-- end entry__thumb -->
                                
                                {% if article.is_special %}

                                    <span class="byline">ویژه</span>

                                {% endif %}
                            <div class="entry__text">
                                <div class="entry__header">
                                    <h1 class="entry__title"><a href="{% url 'blog:detail' article.slug %}" style="font-size:20px;">{{article.title|truncatewords:10}}</a></h1>
                                    
                                    <div class="entry__meta">
                                        <span class="byline">نوشته شده توسط:
                                            <span class='author'>
                                                <a href="{% url 'blog:author' article.author %}">{{article.author.get_full_name}}</a>
                                        </span>
                                    </span>
                                        <span class="cat-links">
                                            {% for cat in article.category.active %}
                                                <a href="{% url 'blog:category' cat.slug %}">,{{cat.title}}</a>
                                            {% endfor %}
                                        </span>
                                    </div>
                                </div>
                                <div class="entry__excerpt">
                                    <p>
                                     {{article.description|safe|truncatewords:22}}
                                    </p>
                                </div>
                                <a class="entry__more-link" style="float:left;" href="{% url 'blog:detail' article.slug %}">بیشتر</a>
                                <a class="entry__more-link" href="{% url 'blog:detail' article.slug %}">{{article.jpublish}}</a>
                            </div> <!-- end entry__text -->
                        
                        </article> <!-- end article -->

                        {% empty %}
                        <h1 class="entry__title">متاسفانه محتوایی برای نمایش وجود ندارد.</h1>
                    {% endfor %}
                    

                </div> <!-- end brick-wrapper -->

            </div> <!-- end masonry -->

            <div class="row">
                <div class="column large-12">
                    <nav class="pgn">
                        {% if page_obj.has_other_pages %}
                        <ul>
                            {% if page_obj.has_previous %}
                                <li>
                                    <a class="pgn__prev" href="{% block previous_page_url %} {% endblock%}">
                                        قبلی
                                    </a>
                                </li>
                            {% else %}
                                <li>
                                    <a class="pgn__prev">
                                        
                                    </a>
                                </li>
                            {% endif %}
                          
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == 1 %}
                                    <li><a class="pgn__num" href="{% block range_1 %} {% endblock %}">{{i}}</a></li>
                                {% else %}
                                    <li><a class="pgn__num" href="{% block range_2 %} {% endblock %}">{{i}}</a></li>
                                {% endif %}
                            {% endfor %}
                       
                            {% if page_obj.has_next %}
                                <li>
                                    <a class="pgn__next" href="{% block next_page_url %} {% endblock %}">
                                        بعدی
                                    </a>
                                </li>
                            {% else %}
                                <li>
                                    <a class="pgn__next">
                                        
                                    </a>
                                </li>
                            {% endif %}


                        </ul>
                    {% endif %}
                    </nav> <!-- end pgn -->
                </div> <!-- end column -->
            </div> <!-- end row -->

        </div> <!-- end s-bricks -->

    </section> <!-- end s-content -->

{% endblock %}

templates/blog/search_list.html
{% extends 'blog/list.html' %}
{% block title %}
جستجو | {{search}}    
{% endblock %}

{% block header %}
<!-- page header
        ================================================== -->
        <div class="s-pageheader">
            <div class="row">
                <div class="column large-12">
                    <h1 class="page-title">
                        <span class="page-title__small-type" style="font-size:30px;">جستجو : {{ search }}</span><br>
                    </h1>
                </div>
            </div>
        </div> 
<!-- end s-pageheader-->
{% endblock %}



{% block previous_page_url %} 
    {% url 'blog:search' page_obj.previous_page_number %}?q={{search}}
{% endblock%}

{% block range_1 %}
    {% url 'blog:search' i %}?q={{search}}
{% endblock %}

{% block range_2 %}
    {% url 'blog:search' i %}?q={{search}}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:search' page_obj.next_page_number %}?q={{search}}
{% endblock %}